
// This file was auto-generated by ML.NET Model Builder. 

using DiabetesModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
DiabetesModel.ModelInput sampleData = new DiabetesModel.ModelInput()
{
    HighBP = 0F,
    HighChol = 0F,
    CholCheck = 0F,
    BMI = 25F,
    Smoker = 1F,
    Stroke = 0F,
    HeartDiseaseorAttack = 0F,
    PhysActivity = 1F,
    Fruits = 0F,
    Veggies = 0F,
    HvyAlcoholConsump = 0F,
    AnyHealthcare = 0F,
    NoDocbcCost = 1F,
    GenHlth = 3F,
    MentHlth = 0F,
    PhysHlth = 0F,
    DiffWalk = 0F,
    Sex = 0F,
    Age = 7F,
    Education = 6F,
    Income = 1F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Diabetes_012 with predicted Diabetes_012 from sample data...\n\n");


Console.WriteLine($"Diabetes_012: {0F}");
Console.WriteLine($"HighBP: {0F}");
Console.WriteLine($"HighChol: {0F}");
Console.WriteLine($"CholCheck: {0F}");
Console.WriteLine($"BMI: {25F}");
Console.WriteLine($"Smoker: {1F}");
Console.WriteLine($"Stroke: {0F}");
Console.WriteLine($"HeartDiseaseorAttack: {0F}");
Console.WriteLine($"PhysActivity: {1F}");
Console.WriteLine($"Fruits: {0F}");
Console.WriteLine($"Veggies: {0F}");
Console.WriteLine($"HvyAlcoholConsump: {0F}");
Console.WriteLine($"AnyHealthcare: {0F}");
Console.WriteLine($"NoDocbcCost: {1F}");
Console.WriteLine($"GenHlth: {3F}");
Console.WriteLine($"MentHlth: {0F}");
Console.WriteLine($"PhysHlth: {0F}");
Console.WriteLine($"DiffWalk: {0F}");
Console.WriteLine($"Sex: {0F}");
Console.WriteLine($"Age: {7F}");
Console.WriteLine($"Education: {6F}");
Console.WriteLine($"Income: {1F}");


var sortedScoresWithLabel = DiabetesModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

